# Generated by Django 5.0.2 on 2024-03-01 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_studentstudydate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstudytime',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='studentstudytime',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='studentstudytime',
            name='seconds',
        ),
        migrations.AddField(
            model_name='studentstudytime',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
