# Generated by Django 5.0.2 on 2024-03-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_user',
            field=models.BooleanField(default=False),
        ),
    ]
